version: "3.8"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Killam@123
  
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  eureka:
    build: ./eureka
    container_name: eureka
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker  

  auth-service:
    build: ./auth
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - eureka
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/auth_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Killam@123

  employee-service:
    build: ./employee
    container_name: employee-service
    ports:
      - "8085:8085"
    depends_on:
      - mysql
      - eureka
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employee_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Killam@123

  compliance-service:
    build: ./compliance
    container_name: compliance-service
    ports:
      - "8084:8084"
    depends_on:
      - mysql
      - eureka
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/compliance_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Killam@123

  policy-service:
    build: ./policy
    container_name: policy-service
    ports:
      - "8086:8086"
    depends_on:
      - mysql
      - eureka
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/policy_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Killam@123

  approval-service:
    build: ./approval
    container_name: approval-service
    ports:
      - "8083:8083"
    depends_on:
      - mysql
      - eureka
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/approval_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Killam@123

  audit-service:
    build: ./audit
    container_name: audit-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - eureka
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/audit_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Killam@123

  notification-service:
    build: ./notification
    container_name: notification-service
    ports:
      - "8087:8087"
    depends_on:
      - mysql
      - eureka
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/notification_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Killam@123

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8088:8088"
    depends_on:
      - eureka
      - auth-service
      - employee-service
      - compliance-service
      - policy-service
      - approval-service
      - audit-service
      - notification-service
    environment:
      SPRING_PROFILES_ACTIVE: docker

volumes:
  mysql-data: