server.port=8087

spring.datasource.url=jdbc:mysql://mysql:3306/notification_db
spring.datasource.username=root
spring.datasource.password=Killam@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

eureka.client.service-url.defaultZone=http://eureka:8761/eureka

eureka.instance.hostname=notification-service
eureka.instance.prefer-ip-address=true