spring.application.name=gateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# ========================
# ROUTES CONFIGURATION
# ========================

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**,/auth-docs/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/auth-docs(?<segment>/?.*),/v3/api-docs${segment}


spring.cloud.gateway.routes[1].id=employee-service
spring.cloud.gateway.routes[1].uri=lb://employee-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/employee/**,/employee-docs/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/employee-docs(?<segment>/?.*),/v3/api-docs${segment}


spring.cloud.gateway.routes[2].id=audit-service
spring.cloud.gateway.routes[2].uri=lb://audit-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/audit/**,/audit-docs/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/audit-docs(?<segment>/?.*),/v3/api-docs${segment}


spring.cloud.gateway.routes[3].id=approval-service
spring.cloud.gateway.routes[3].uri=lb://approval-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/approval/**,/approval-docs/**
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/approval-docs(?<segment>/?.*),/v3/api-docs${segment}


spring.cloud.gateway.routes[4].id=compliance-service
spring.cloud.gateway.routes[4].uri=lb://compliance-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/compliance/**, /compliance-docs/**
spring.cloud.gateway.routes[4].filters[0]=RewritePath=/compliance-docs(?<segment>/?.*),/v3/api-docs${segment}

spring.cloud.gateway.routes[5].id=policy-service
spring.cloud.gateway.routes[5].uri=lb://policy-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/policy/**, /policy-docs/**
spring.cloud.gateway.routes[5].filters[0]=RewritePath=/policy-docs(?<segment>/?.*),/v3/api-docs${segment}

spring.cloud.gateway.routes[6].id=notification-service
spring.cloud.gateway.routes[6].uri=lb://notification-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/notification/**, /notification-docs/**
spring.cloud.gateway.routes[6].filters[0]=RewritePath=/notification-docs(?<segment>/?.*),/v3/api-docs${segment}



# ==============================
# SWAGGER AGGREGATION
# ==============================

springdoc.swagger-ui.urls[0].name=auth-service
springdoc.swagger-ui.urls[0].url=/auth-docs

springdoc.swagger-ui.urls[1].name=employee-service
springdoc.swagger-ui.urls[1].url=/employee-docs

springdoc.swagger-ui.urls[2].name=audit-service
springdoc.swagger-ui.urls[2].url=/audit-docs

springdoc.swagger-ui.urls[3].name=approval-service
springdoc.swagger-ui.urls[3].url=/approval-docs

springdoc.swagger-ui.urls[4].name=compliance-service
springdoc.swagger-ui.urls[4].url=/compliance-docs

springdoc.swagger-ui.urls[5].name=policy-service
springdoc.swagger-ui.urls[5].url=/policy-docs

springdoc.swagger-ui.urls[6].name=notification-service
springdoc.swagger-ui.urls[6].url=/notification-docs
      
server.port=8080