spring.application.name=auth-service

spring.profiles.active=dev

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.serialization.fail-on-empty-beans=false

jwt.secret=your-very-secure-secret-key-your-very-secure-secret-key

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true